---

- name: Configuramos servidor NFS en CentOS
  hosts: centos
  become: true

  vars:
    nfs_export_dir: /var/nfs_shared
    nfs_export_opts: "*(rw,sync,no_subtree_check)" 

  tasks:

    - name: TAREA#1 Asegurar paquetes requeridos instalados
      ansible.builtin.package:
        name:
          - nfs-utils
          - firewalld
        state: present

    - name: TAREA#2 Asegurar firewalld iniciado y habilitado
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: yes

    - name: TAREA#3 Permitir TCP 2049 en el firewall
      ansible.posix.firewalld:
        port: 2049/tcp
        permanent: yes
        state: enabled
        immediate: yes

    - name: TAREA#4 Permitir UDP 2049 en el firewall
      ansible.posix.firewalld:
        port: 2049/udp
        permanent: yes
        state: enabled
        immediate: yes

    - name: TAREA#5 Creamos /var/nfs_shared con nobody:nobody y 0777
      ansible.builtin.file:
        path: "{{ nfs_export_dir }}"
        state: directory
        owner: nobody
        group: nobody
        mode: "0777"

    - name: TAREA#6 Declaramos export en /etc/exports
      ansible.builtin.blockinfile:
        path: /etc/exports
        marker: "# {mark} ANSIBLE MANAGED NFS EXPORT"
        block: |
          {{ nfs_export_dir }} {{ nfs_export_opts }}
      notify: TAREA#8 Recargar exports NFS

    - name: TAREA#7 Aseguramos que el servicio NFS este iniciado y habilitado
      ansible.builtin.service:
        name: nfs-server
        state: started
        enabled: yes

  handlers:
    - name: TAREA#8 Recarga exports NFS
      ansible.builtin.command: exportfs -ra
      notify: TAREA#9 Recargar servicio nfs-server

    - name: TAREA#9 Recarga servicio nfs-server
      ansible.builtin.service:
        name: nfs-server
        state: reloaded
